### ISSUE TITLE
importError 

### ISSUE THREAD

**Issue by tjusxh** [stdcoutzyx/FaceRetrieval#1]
Traceback (most recent call last):
  File "retrieval/retrieve.py", line 4, in <module>
    from retrieval.load_data import *
ImportError: No module named retrieval.load_data

How to deal with the question?Thank you!

**Comment by Newman101** [comment]
Hi, is this still an issue? I can try and replicate the error.

**Comment by stdcoutzyx** [comment]
yeah, i forget to describe that clearly, u need to set the python path first, for example, u have downloaded the project into /home/yourname/image_retrieval. u should add this path /home/yourname/image_retrieval/src into your python sys.path. u can simply add the path by write a my.pth file in the python's third library folder whose name is "site-packages"

**Comment by dylansun** [comment]
Hi @stdcoutzyx , I create a `setup.py` file:

#!/usr/bin/env python

from distutils.core import setup

setup(name='faceretrieval',
      version='1.0',
      description='Test',
      author='Test',
      author_email='Test',
      url='url',
      packages=['retrieval', 'data_prepare'],
     )

And then use the python command `python setup.py sdist` to generate a package and install.

**Comment by stdcoutzyx** [comment]
yeah, @dylansun , that's very cool, thanks.
